{% set name = "napari-signal-selector" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-signal-selector-{{ version }}.tar.gz
  sha256: 66c2131a096fefa1eff0b91c7bf4bbb43a89f6e71868d287c0006feedb73fbdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
  run:
    - cmap
    - magicgui
    - napari-matplotlib >=1.1.0
    - napari-skimage-regionprops
    - numpy
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_signal_selector
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-signal-selector
  summary: An interactive signal selector for napari, based on napari-matplotlib.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/zoccoler/napari-signal-selector

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - zoccoler
